// Date: 22.01.2013 16:53:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.dcm;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDiscoCreeper extends ModelBase
{
	
	public float HeadRot;
	public float HeadSpeed = 0.5F;
  //fields
    ModelRenderer head;
    ModelRenderer body3;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer body;
    ModelRenderer body2;
  
  public ModelDiscoCreeper()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -20F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 94, 16);
      body3.addBox(-4F, -12F, -2F, 8, 4, 4);
      body3.setRotationPoint(0F, 0F, 0F);
      body3.setTextureSize(128, 64);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 16);
      leg3.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg3.setRotationPoint(-2F, 18F, -4F);
      leg3.setTextureSize(128, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 16);
      leg4.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg4.setRotationPoint(2F, 18F, -4F);
      leg4.setTextureSize(128, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 16);
      leg1.addBox(0F, 0F, -2F, 4, 6, 4);
      leg1.setRotationPoint(-4F, 18F, 4F);
      leg1.setTextureSize(128, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 16);
      leg2.addBox(-2F, 0F, -2F, 4, 6, 4);
      leg2.setRotationPoint(2F, 18F, 4F);
      leg2.setTextureSize(128, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      body = new ModelRenderer(this, 42, 16);
      body.addBox(-4F, -4F, -2F, 8, 4, 4);
      body.setRotationPoint(0F, 18F, 0F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 67, 16);
      body2.addBox(-4F, -8F, -2F, 8, 4, 4);
      body2.setRotationPoint(0F, 0F, 0F);
      body2.setTextureSize(128, 64);
      body2.mirror = true;
      setRotation(body2, 0F, 0F, 0F);
      
      body.addChild(body2);
      body2.addChild(body3);
      body3.addChild(head);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg3.render(f5);
    leg4.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    body.render(f5);
    
    if(HeadRot >= 0.0F){
    	 HeadSpeed-= 0.01F;
    	}
    	else if(HeadRot <-0.0F){
    	 HeadSpeed+=0.04F;
    	}
    	HeadRot+= HeadSpeed;
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    body.rotateAngleX = HeadRot/100;
    body2.rotateAngleX = HeadRot/100;
    body3.rotateAngleX = HeadRot/100;
    head.rotateAngleX = HeadRot/100;
    
    body.rotateAngleY = HeadRot/100;
    body2.rotateAngleY = HeadRot/100;
    body3.rotateAngleY = HeadRot/100;
    head.rotateAngleY = HeadRot/100;
    
    
  }
  
  
  
}
